# Generated by Django 6.0.4 on 2026-09-15 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_course_enrollment_savedcourse"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="category",
            field=models.CharField(default="Development", max_length=100),
        ),
    ]
