# Generated by Django 6.0.4 on 2026-09-16 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_course_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="lessons",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="course",
            name="role",
            field=models.CharField(default="Teacher", max_length=150),
        ),
    ]
