# Generated by Django 6.0.4 on 2026-10-06 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_course_lessons_course_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section", models.CharField(default="Module 1", max_length=200)),
                ("section_order", models.PositiveIntegerField(default=1)),
                ("title", models.CharField(max_length=255)),
                ("duration", models.CharField(default="5:00", max_length=20)),
                ("order", models.PositiveIntegerField(default=1)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("video", "Video"),
                            ("reading", "Reading"),
                            ("quiz", "Quiz"),
                        ],
                        default="video",
                        max_length=20,
                    ),
                ),
                ("video_url", models.URLField(blank=True, default="")),
                ("description", models.TextField(blank=True, default="")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_items",
                        to="accounts.course",
                    ),
                ),
            ],
            options={
                "ordering": ["section_order", "order"],
                "unique_together": {("course", "section_order", "order")},
            },
        ),
        migrations.CreateModel(
            name="LessonProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="accounts.lesson",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "lesson")},
            },
        ),
    ]
