# Generated by Django 6.1.2 on 2026-10-07 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_lesson_lessonprogress"),
    ]

    operations = [
        migrations.CreateModel(
            name="FooterColumn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Ex: Nanodegrees, Programas, Sobre", max_length=100
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Footer Column",
                "verbose_name_plural": "Footer Columns",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="FooterPodcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "heading",
                    models.CharField(default="Ouça Nossos Podcasts", max_length=100),
                ),
                (
                    "spotify_url",
                    models.URLField(blank=True, default="https://open.spotify.com"),
                ),
                (
                    "google_podcasts_url",
                    models.URLField(blank=True, default="https://podcasts.google.com"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Footer Podcast",
                "verbose_name_plural": "Footer Podcasts",
            },
        ),
        migrations.CreateModel(
            name="FooterSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "copyright_text",
                    models.CharField(
                        default="Todos os direitos reservados",
                        help_text="Suffix after 'Kutiva YYYY.' — PT text; EN uses i18n suffix",
                        max_length=200,
                    ),
                ),
                (
                    "copyright_text_en",
                    models.CharField(
                        blank=True, default="All rights reserved", max_length=200
                    ),
                ),
            ],
            options={
                "verbose_name": "Footer Settings",
                "verbose_name_plural": "Footer Settings",
            },
        ),
        migrations.CreateModel(
            name="FooterSocial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("facebook", "Facebook"),
                            ("github", "GitHub"),
                            ("twitter", "Twitter"),
                            ("youtube", "YouTube"),
                            ("instagram", "Instagram"),
                            ("linkedin", "LinkedIn"),
                            ("spotify", "Spotify"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("url", models.URLField(default="#")),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Footer Social Link",
                "verbose_name_plural": "Footer Social Links",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="FooterLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                (
                    "url",
                    models.CharField(default="#", help_text="URL or #", max_length=500),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "column",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="accounts.footercolumn",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
